nginx:
  image: jemoon/magento-nginx:1.0
  environment:
    PHP_HOST: ${FPM_HOST}
    PHP_PORT: ${FPM_PORT}
    ENCRYPTIONKEY: ${ENC_KEY}
    ADMIN_FRONTNAME: ${ADMIN_NAME}
    MYSQL_HOST: ${MYSQL_HOST}
    MYSQL_DATABASE: ${MYSQL_DB}
    MYSQL_USER: ${MYSQL_USER}
    MYSQL_PASSWORD: ${MYSQL_PASS}
  container_name: nginx
  ports:
    - "80:80"
    - "443:443"
  links:
    - "php"
  volumes_from:
    - src-nginx
  labels:
    io.rancher.sidekicks: src-nginx
    io.rancher.scheduler.affinity:host_label: ${KEY}=${VALUE}
php:
  image: jemoon/magento-php:1.0
  container_name: php-fpm
  links:
    - "cache:rediscache"
    - "sessions:redissession"
    - "fpc:redisfpc"
    - "mysql:mysql"
  labels:
    io.rancher.sidekicks: src-php
    io.rancher.scheduler.affinity:host_label: ${KEY}=${VALUE}
  volumes_from:
    - src-php
src-php:
  image: tianon/true
  labels:
    io.rancher.scheduler.affinity:host_label: ${KEY}=${VALUE}
  volumes:
    - ${APP_LOCATION}:/var/www/html
src-nginx:
  image: tianon/true
  labels:
    io.rancher.scheduler.affinity:host_label: ${KEY}=${VALUE}
  volumes:
    - ${APP_LOCATION}:/var/www/html
mysql:
  image: percona:latest
  container_name: percona
  ports:
    - "3306:3306"
  volumes:
    - ${MYSQL_LOCATION}:/var/lib/mysql
  labels:
    io.rancher.scheduler.affinity:host_label: ${KEY}=${VALUE}
cache:
  image: redis:latest
  container_name: redis-cache
  labels:
    io.rancher.scheduler.affinity:host_label: ${KEY}=${VALUE}
fpc:
  image: redis:latest
  container_name: redis-fpc
  labels:
    io.rancher.scheduler.affinity:host_label: ${KEY}=${VALUE}
sessions:
  image: redis:latest
  container_name: redis-sessions
  labels:
    io.rancher.scheduler.affinity:host_label: ${KEY}=${VALUE}
