nginx:
  image: jemoon/magento-nginx:1.0
  environment:
    PHP_HOST: ${fpm-host}
    PHP_PORT: ${fpm-port}
    ENCRYPTIONKEY: ${enc-key}
    ADMIN_FRONTNAME: ${admin-name}
    MYSQL_HOST: ${mysql-host}
    MYSQL_DATABASE: ${mysql-db}
    MYSQL_USER: ${mysql-user}
    MYSQL_PASSWORD: ${mysql-pass}
  container_name: nginx
  ports:
    - "80:80"
    - "443:443"
  links:
    - "php"
  volumes_from:
    - php
php:
  image: jemoon/magento-php:1.0
  container_name: php-fpm
  links:
    - "cache:rediscache"
    - "sessions:redissession"
    - "fpc:redisfpc"
    - "mysql:mysql"
  volumes:
    - ${app-location}:/var/www/html
mysql:
  image: percona:latest
  container_name: percona
  ports:
    - "3306:3306"
  volumes:
    - ${mysql-location}:/var/lib/mysql
cache:
  image: redis:latest
  container_name: redis-cache
fpc:
  image: redis:latest
  container_name: redis-fpc
sessions:
  image: redis:latest
  container_name: redis-sessions