nginx:
  image: jemoon/magento-nginx-php:1.0
  container_name: nginx-php
  ports:
    - "80:80"
    - "443:443"
  volumes_from:
    - data
  links:
    - "cache:rediscache"
    - "sessions:redissession"
    - "fpc:redisfpc"
    - "mysql:mysql"
  labels:
    io.rancher.sidekicks: data
    io.rancher.scheduler.affinity:host_label: ${KEY}=${VALUE}
data:
  image: tianon/true
  container_name: data
  volumes:
    - ${APP_LOCATION}:/var/www/html
mysql:
  image: percona:latest
  container_name: percona
  volumes:
    - ${MYSQL_LOCATION}:/var/lib/mysql
  labels:
    io.rancher.scheduler.affinity:host_label: ${KEY}=${VALUE}
cache:
  image: redis:latest
  container_name: redis-cache
  labels:
    io.rancher.scheduler.affinity:host_label: ${KEY}=${VALUE}
fpc:
  image: redis:latest
  container_name: redis-fpc
  labels:
    io.rancher.scheduler.affinity:host_label: ${KEY}=${VALUE}
sessions:
  image: redis:latest
  container_name: redis-sessions
  labels:
    io.rancher.scheduler.affinity:host_label: ${KEY}=${VALUE}