nginx:
  image: jemoon/magento-nginx:1.0
  environment:
    PHP_HOST: ${fpm-host}
    PHP_PORT: 9000
    ENCRYPTIONKEY: a918a01cbbdfc27580760640f93fe1a9
    ADMIN_FRONTNAME: adminJemiol
    MYSQL_HOST: mysql
    MYSQL_DATABASE: jemiol
    MYSQL_USER: root
    MYSQL_PASSWORD: root
  container_name: nginx
  ports:
    - "80:80"
    - "443:443"
  links:
    - "php"
  volumes_from:
    - php
php:
  image: jemoon/magento-php:1.0
  container_name: php-fpm
  links:
    - "cache:rediscache"
    - "sessions:redissession"
    - "fpc:redisfpc"
    - "mysql:mysql"
  volumes:
    - /var/www/jemiol.dev/src:/var/www/html
mysql:
  image: percona:latest
  container_name: percona
  ports:
    - "3306:3306"
  volumes:
    - /var/lib/mysql:/var/lib/mysql
cache:
  image: redis:latest
  container_name: redis-cache
fpc:
  image: redis:latest
  container_name: redis-fpc
sessions:
  image: redis:latest
  container_name: redis-sessions